# Generated by Django 4.2.3 on 2023-08-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('contentBox', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='contactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('emailId', models.EmailField(max_length=254)),
                ('phoneNo', models.CharField(max_length=12)),
                ('subject', models.CharField(max_length=100)),
                ('messageContent', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='popularblog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('contentBox', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='recentlyAdded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('contentBox', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WebBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('contentBox', models.TextField()),
            ],
        ),
    ]
