# Generated by Django 4.2.3 on 2023-08-09 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appblog',
            name='imageBox',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='webBlog/'),
        ),
        migrations.AddField(
            model_name='popularblog',
            name='imageBox',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='webBlog/'),
        ),
        migrations.AddField(
            model_name='recentlyadded',
            name='imageBox',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='webBlog/'),
        ),
        migrations.AddField(
            model_name='webblog',
            name='imageBox',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='webBlog/'),
        ),
    ]
