# Generated by Django 4.2.3 on 2023-08-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_appblog_imagebox_popularblog_imagebox_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentlyadded',
            name='imageBox',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='recentBlog/'),
        ),
    ]
