# Generated by Django 4.2.3 on 2023-08-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_recentlyadded_imagebox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appblog',
            name='imageBox',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='appBlog/'),
        ),
    ]
